site_name: PRoot Development Blog
site_author: Lucas Ramage
site_url: https://proot-me.github.io/blog

theme:
  name: gitbook

docs_dir: posts

plugins:
  - autolinks
  - git-authors

repo_url: https://github.com/proot-me/blog.git
